let sTenUnit = '(万元)';    //万元单位
let sNumUnit = '(数量)';    //数量单位
let sPriceUnit = '(金额)';  //金额单位

//如果文字过长 设置列的宽度
function fnTiteWidth(title) {
  return (title.includes(sTenUnit) || title.includes(sNumUnit) || title.includes(sPriceUnit)) ? Number(title.length) * 15 : Number(title.length) * 16;
}

export let totalColumn = [
  {
    type: "seq",
    title: "序号",
    fixed: 'left',
    width: 35,
    align: "center",
  },
  {
    field: "businessCenter",
    title: "业务中心",
    align: "left",
    width: 120,
    type: "html",
  },
  {
    field: "businessUnit",
    title: "业务单元",
    align: "center",
    width: 120,
    type: "html",
  },
  {
    field: "followUpPeople",
    title: "跟进人",
    align: "center",
    type: "html",
  },
  {
    field: "pageNum",
    title: "营销立项数",
    align: "center",
    type: "html",
  },
  {
    field: "gczj",
    title: `工程造价${sTenUnit}`,
    align: "center",
    width: fnTiteWidth(`工程造价${sTenUnit}`),
    type: "html",
  },
  {
    field: "curYearNum",
    title: "本年累计营销立项数",
    align: "center",
    width: fnTiteWidth('本年累计营销立项数'),
    type: "html",
  },
  {
    field: "curYeargczj",
    title: `本年累计工程造价${sTenUnit}`,
    align: "center",
    width: fnTiteWidth(`本年累计工程造价${sTenUnit}`),
    type: "html",
  },
  // {  //需求调整 暂时去掉这些字段
  //   field: "auditNum",
  //   title: "审核数",
  //   align: "center",
  //   type: "html",
  // },
  // {
  //   field: "auditPrice",
  //   title: "审核金额",
  //   align: "center",
  //   type: "html",
  // },
  // {
  //   field: "curYeanAuditNum",
  //   title: "本年审核数",
  //   align: "center",
  //   type: "html",
  // },
  // {
  //   field: "curYeanauditPrice",
  //   title: "本年审金额",
  //   align: "center",
  //   type: "html",
  // },
  {
    field: "bidNum",
    title: "投标数量",
    align: "center",
    type: "html",
  },
  {
    field: "tbPrice",
    title: `投标金额${sTenUnit}`,
    width: fnTiteWidth(`投标金额${sTenUnit}`),
    align: "center",
    type: "html",
  },
  {
    field: "dqdttbl",
    title: "当期单体投标量",
    width: fnTiteWidth('当期单体投标量'),
    align: "center",
    type: "html",
  },
  {
    field: "curYearBidNum",
    title: "本年投标数量",
    width: fnTiteWidth('本年投标数量'),
    align: "center",
    type: "html",
  },
  {
    field: "curYearBidPrice",
    title: `本年投标金额${sTenUnit}`,
    width: fnTiteWidth(`本年投标金额${sTenUnit}`),
    align: "center",
    type: "html",
  },
  {
    field: "curYearBidl",
    title: `本年单体投标量${sTenUnit}`,
    width: fnTiteWidth(`本年单体投标量${sTenUnit}`),
    align: "center",
    type: "html",
  },
  // {  //需求调整 暂时去掉这些字段
  //   field: "zgshNum",
  //   title: "资格审核个数",
  //   width: fnTiteWidth(`资格审核个数`),
  //   align: "center",
  //   type: "html",
  // },
  // {
  //   field: "zgshPrice",
  //   title: `资格审核金额${sTenUnit}`,
  //   width: fnTiteWidth(`资格审核金额${sTenUnit}`),
  //   align: "center",
  //   type: "html",
  // },
  // {
  //   field: "curYearzgshNum",
  //   title: "本年资格审核个数",
  //   width: fnTiteWidth(`本年资格审核个数`),
  //   align: "center",
  //   type: "html",
  // },
  // {
  //   field: "curYearzgshprice",
  //   title: `本年资格审核金额${sTenUnit}`,
  //   width: fnTiteWidth(`本年资格审核金额${sTenUnit}`),
  //   align: "center",
  //   type: "html",
  // },
  {
    field: "zbsl",
    title: "中标数量",
    align: "center",
    type: "html",
  },
  {
    field: 'zbje',
    title: `中标金额${sTenUnit}`,
    width: fnTiteWidth(`中标金额${sTenUnit}`),
    align: 'center',
    type: 'html'
  },
  {
    field: "dqdtBidl",
    title: `当期单体中标量${sTenUnit}`,
    width: fnTiteWidth(`当期单体中标量${sTenUnit}`),
    align: "center",
    type: "html",
  },
  {
    field: "bnzbl",
    title: "本年中标量",
    align: "center",
    type: "html",
  },
  {
    field: "curYearBidPrice",
    title: "本年中标金额",
    width: fnTiteWidth(`本年中标金额`),
    align: "center",
    type: "html",
  },
  {
    field: "bndtzbl",
    title: `本年单体中标量${sTenUnit}`,
    width: fnTiteWidth(`本年单体中标量${sTenUnit}`),
    align: "center",
    type: "html",
  },
  {
    field: "bidPercentNum",
    title: `投标转化率${sNumUnit}`,
    width: fnTiteWidth(`投标转化率${sNumUnit}`),
    align: "center",
    type: "html",
  },
  {
    field: "bidPercentPrice",
    title: `投标转化率${sPriceUnit}`,
    width: fnTiteWidth(`投标转化率${sPriceUnit}`),
    align: "center",
    type: "html",
  },
  {
    field: "zbPercentNum",
    title: `中标转化率${sNumUnit}`,
    width: fnTiteWidth(`中标转化率${sNumUnit}`),
    align: "center",
    type: "html",
  },
  {
    field: "zbPercentPrice",
    title: `中标转化率${sPriceUnit}`,
    width: fnTiteWidth(`中标转化率${sPriceUnit}`),
    align: "center",
    type: "html",
  },
  {
    field: "lxwtbNum",
    title: "已立项未投标数量",
    width: fnTiteWidth(`已立项未投标数量`),
    align: "center",
    type: "html",
  },
  {
    field: "lxwtbygPrice",
    title: `已立项未投标预估金额${sTenUnit}`,
    width: fnTiteWidth(`已立项未投标预估金额${sTenUnit}`),
    align: "center",
    type: "html",
  },
  {
    field: "ztNum",
    title: "在投数量",
    align: "center",
    type: "html",
  },
  {
    field: "ygtbPrice",
    title: `预估投标金额${sTenUnit}`,
    width: fnTiteWidth(`预估投标金额${sTenUnit} `),
    align: "center",
    type: "html",
  },
  {
    field: "ytNum",
    title: "已投待定数量",
    align: "center",
    type: "html",
  },
  {
    field: "bidPrice",
    title: `已投待定金额${sTenUnit}`,
    width: fnTiteWidth(`已投待定金额${sTenUnit}`),
    align: "center",
    type: "html",
  },
  {
    field: "abandonFolowUpNum",
    title: "放弃跟进数",
    align: "center",
    type: "html",
  },
  {
    field: "abandonFolowUpPrice",
    title: `放弃跟进金额${sTenUnit}`,
    width: fnTiteWidth(`放弃跟进金额${sTenUnit}`),
    align: "center",
    type: "html",
  },
  {
    field: "xmlxNum",
    title: "项目立项个数",
    width: fnTiteWidth(`项目立项个数`),
    align: "center",
    type: "html",
  },
  {
    field: "signContractNum",
    title: "已签合同个数",
    width: fnTiteWidth(`已签合同个数`),
    align: "center",
    type: "html",
  },
  {
    field: "signContractPrice",
    title: "已签合同金额",
    width: fnTiteWidth(`已签合同金额`),
    align: "center",
    type: "html",
  }
]